name: Sync fork

on:
  schedule:
    - cron: "0 0 * * *" # Every midnight UTC
  workflow_dispatch:

env:
  GITHUB_USERNAME: Izn432
  GITHUB_ORG: CATcher-org
  REPO_NAME: WATcher

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone the fork
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/${{ env.GITHUB_ORG }}/${{ env.REPO_NAME }}.git repo
          
      - name: Sync with upstream
        working-directory: repo
        run: |
          git remote add upstream https://github.com/${{ env.GITHUB_ORG }}/${{ env.REPO_NAME }}.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git push origin HEAD
