name: Sync fork

on:
  schedule:
    - cron: "0 0 * * *" # Every midnight UTC
  workflow_dispatch:

env:
  GITHUB_USERNAME: Izn432

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - { name: "WATcher", org: "CATcher-org", branch: "main" }
          - { name: "CATcher", org: "CATcher-org", branch: "master" }
    steps:
      - uses: actions/checkout@v4

      - name: Clone the fork
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/${{ env.GITHUB_USERNAME }}/${{ matrix.repo.name }}.git repo
          
      - name: Sync with upstream
        working-directory: repo
        run: |
          git remote add upstream https://github.com/${{ matrix.repo.org }}/${{ matrix.repo.name }}.git
          git fetch upstream
          git checkout ${{ matrix.repo.branch }}
          git merge upstream/${{ matrix.repo.branch }} --no-edit
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ env.GITHUB_USERNAME }}/${{ matrix.repo.name }}.git main
